// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs8WdhwtSm62l2z--EJ_h6A8ZPbmpoboU',
    appId: '1:1083845187301:web:ff6b80e879fc293f78260c',
    messagingSenderId: '1083845187301',
    projectId: 'allahualam-74519',
    authDomain: 'allahualam-74519.firebaseapp.com',
    storageBucket: 'allahualam-74519.firebasestorage.app',
    measurementId: 'G-SC7BNZWLL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGKfwYU3DRuvolSD2X2Dw0uRxpYT-8DCI',
    appId: '1:1083845187301:android:533617799cd88c7978260c',
    messagingSenderId: '1083845187301',
    projectId: 'allahualam-74519',
    storageBucket: 'allahualam-74519.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBug8Qbw-NxRUNxJF5gtgU5ZCDasuoLO8',
    appId: '1:1083845187301:ios:28a49aa1d7a7381d78260c',
    messagingSenderId: '1083845187301',
    projectId: 'allahualam-74519',
    storageBucket: 'allahualam-74519.firebasestorage.app',
    iosBundleId: 'com.example.allahHoAllamFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBug8Qbw-NxRUNxJF5gtgU5ZCDasuoLO8',
    appId: '1:1083845187301:ios:28a49aa1d7a7381d78260c',
    messagingSenderId: '1083845187301',
    projectId: 'allahualam-74519',
    storageBucket: 'allahualam-74519.firebasestorage.app',
    iosBundleId: 'com.example.allahHoAllamFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs8WdhwtSm62l2z--EJ_h6A8ZPbmpoboU',
    appId: '1:1083845187301:web:38cea47254ab958c78260c',
    messagingSenderId: '1083845187301',
    projectId: 'allahualam-74519',
    authDomain: 'allahualam-74519.firebaseapp.com',
    storageBucket: 'allahualam-74519.firebasestorage.app',
    measurementId: 'G-H43F9L6XQ8',
  );
}
